const STORAGE_KEY = 'lemar_metas_monitores_v1';
const MAX_PAYMENT = 840;
const RULES = [
  {id:'rnc',name:'RNC por responsabilidade por milhão de km',type:'SETOR',better:'menor',weight:20,target:21,unit:'índice',format:v=>fmt(v,1),attain:v=>v<=21?1.2:0,range:'Até 21,0'},
  {id:'dss',name:'DSS realizados presencialmente',type:'INDIVIDUAL',better:'maior',weight:25,target:40,unit:'quantidade',format:v=>fmt(v,0),attain:v=>v<32?0:v<40?.8:v<48?1:1.2,range:'32 / 40 / 48'},
  {id:'speed',name:'Alertas de velocidade por milhão de km',type:'SETOR',better:'menor',weight:10,target:12000,unit:'índice',format:v=>fmt(v,0),attain:v=>v<=12000?1.2:0,range:'Até 12.000'},
  {id:'disciplinary',name:'Tratativa das orientações disciplinares',type:'SETOR',better:'maior',weight:30,target:.8,unit:'percentual',format:v=>pct(v),attain:v=>v>=.8?1.2:0,range:'80% ou mais'},
  {id:'critical',name:'Acompanhamento de motoristas críticos',type:'INDIVIDUAL',better:'maior',weight:15,target:2,unit:'quantidade',format:v=>fmt(v,0),attain:v=>v<1?0:v<2?.8:v<3?1:1.2,range:'1 / 2 / 3'}
];
const defaultState={version:1,activeMonth:new Date().toISOString().slice(0,7),monitors:[],months:{}};
let state=loadState();let currentView='general';

const el=id=>document.getElementById(id);const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v);const fmt=(v,d=0)=>Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d});const pct=v=>`${fmt((v||0)*100,0)}%`;const monthLabel=m=>{const [y,mo]=m.split('-');return new Date(Number(y),Number(mo)-1,1).toLocaleDateString('pt-BR',{month:'long',year:'numeric'})};
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||structuredClone(defaultState)}catch{return structuredClone(defaultState)}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));render()}
function monthData(id){state.months[state.activeMonth]??={};state.months[state.activeMonth][id]??={};return state.months[state.activeMonth][id]}
function score(id){const values=monthData(id);const goals=RULES.map(r=>{const raw=values[r.id];const has=raw!==undefined&&raw!==null&&raw!=='';const a=has?r.attain(Number(raw)):0;return {...r,raw,has,attainment:a,points:r.weight*a}});const points=goals.reduce((s,g)=>s+g.points,0);const payment=points<80?0:points<100?560:points<120?700:840;return{goals,points,payment,missed:MAX_PAYMENT-payment,band:points<80?0:points<100?80:points<120?100:120}}
function initials(name){return name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function toast(msg){const t=el('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function renderNav(){el('monitorNav').innerHTML=state.monitors.map(m=>`<button class="nav-item ${currentView===m.id?'active':''}" data-view="${esc(m.id)}"><span class="avatar">${esc(initials(m.name))}</span><span><strong>${esc(m.name)}</strong><small>${score(m.id).points.toFixed(0)} pontos</small></span></button>`).join('');document.querySelector('.nav-item.general').classList.toggle('active',currentView==='general');document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;render()})}
function reportHeader(label){return `<div class="report-header"><div class="report-brand-wrap"><img class="report-logo" src="assets/logo-ssma.png" alt="Logo SSMA"><div class="report-brand">LEMAR <span style="color:#b49200">TRANSPORTES</span><small style="display:block;font-size:11px;letter-spacing:.08em;color:#666;margin-top:3px">SEGURANÇA • SAÚDE • MEIO AMBIENTE</small></div></div><div class="report-meta"><strong>${esc(label)}</strong><br>${monthLabel(state.activeMonth)}</div></div>`}
function render(){el('monthInput').value=state.activeMonth;renderNav();if(currentView==='general')renderGeneral();else{const m=state.monitors.find(x=>x.id===currentView);if(!m){currentView='general';return render()}renderIndividual(m)}}
function kpis(s){return `<div class="kpi-grid"><div class="kpi green"><small>Valor a receber</small><strong>${money(s.payment)}</strong><span class="value-pill green">Crédito do mês</span></div><div class="kpi red"><small>Deixou de receber</small><strong>${money(s.missed)}</strong><span class="value-pill red">Em relação ao máximo</span></div><div class="kpi yellow"><small>Pontuação total</small><strong>${fmt(s.points,0)} pts</strong><span>Máximo: 120 pontos</span></div><div class="kpi"><small>Faixa atingida</small><strong>${s.band}%</strong><span>${s.band===120?'Superação máxima':s.band===100?'Meta atingida':s.band===80?'Faixa inicial':'Abaixo do mínimo'}</span></div></div>`}
function analysis(s){const weak=s.goals.filter(g=>g.attainment<1.2);if(!weak.length)return 'Resultado máximo: todas as metas atingiram a faixa de 120%. O foco agora é manter a consistência no próximo ciclo.';const zero=weak.filter(g=>g.attainment===0);const names=(zero.length?zero:weak).map(g=>g.name).join(', ');return `${s.band>=100?'Bom resultado no ciclo.':'O resultado exige atenção.'} ${zero.length?'As metas sem pontuação foram':'As principais oportunidades de evolução são'}: ${names}. A diferença para o pagamento máximo é de ${money(s.missed)}.`}
function renderIndividual(m){const s=score(m.id);el('mainContent').innerHTML=`${reportHeader(`Relatório individual — ${m.name}`)}<section class="page-head"><div><div class="eyebrow">RELATÓRIO INDIVIDUAL • ${monthLabel(state.activeMonth).toUpperCase()}</div><h1>${esc(m.name)}</h1><p>Desempenho, remuneração e oportunidades de evolução.</p></div><div class="actions no-print"><button class="btn secondary" id="renameBtn">Renomear</button><button class="btn danger" id="deleteBtn">Excluir</button><button class="btn dark" id="printBtn">Exportar PDF individual</button></div></section>${kpis(s)}<div class="grid-2"><section class="panel"><div class="panel-head"><div><h2>Resultado por meta</h2><span class="panel-sub">Os campos amarelos são editáveis</span></div></div><div class="goal-list">${s.goals.map(g=>goalRow(m,g)).join('')}</div></section><section><div class="panel"><div class="panel-head"><h2>Distribuição dos pontos</h2><span class="panel-sub">por indicador</span></div><div class="chart-list">${s.goals.map(g=>`<div class="chart-item"><header><span>${shortName(g.name)}</span><strong>${fmt(g.points,1)} / ${fmt(g.weight*1.2,0)}</strong></header><div class="chart-track"><div class="chart-fill ${g.attainment===1.2?'green':''}" style="width:${Math.min(100,g.attainment/1.2*100)}%"></div></div></div>`).join('')}</div></div><div class="analysis-box"><h3>Análise do desempenho</h3><p>${analysis(s)}</p></div></section></div>`;bindIndividual(m)}
function shortName(n){return n.replace('INDICADOR DE ','').replace('ÍNDICE DE ','').replace(' por milhão de km','').slice(0,44)}
function goalRow(m,g){const cls=g.attainment===1.2?'good':g.attainment>=.8?'warn':'bad';const isPercent=g.unit==='percentual';const displayValue=g.has?(isPercent?Number(g.raw)*100:g.raw):'';return `<div class="goal-row"><div class="goal-title"><strong>${g.name}</strong><small>${g.type} • Peso ${g.weight} • Meta: ${g.range}</small></div><input class="actual-input" type="number" step="1" min="0" ${isPercent?'max="100"':''} value="${displayValue}" data-monitor="${esc(m.id)}" data-goal="${g.id}" data-percent="${isPercent}" aria-label="Real do mês para ${g.name}"><div class="attainment ${cls}">${pct(g.attainment)}</div><div class="points">${fmt(g.points,1)} pts</div></div>`}
function bindIndividual(m){document.querySelectorAll('.actual-input').forEach(input=>input.onchange=()=>{monthData(input.dataset.monitor)[input.dataset.goal]=input.value===''?null:(input.dataset.percent==='true'?Number(input.value)/100:Number(input.value));saveState()});el('printBtn').onclick=()=>window.print();el('renameBtn').onclick=()=>{const n=prompt('Novo nome do monitor:',m.name)?.trim();if(n){m.name=n;saveState()}};el('deleteBtn').onclick=()=>{if(confirm(`Excluir ${m.name}? O histórico deste monitor também será removido.`)){state.monitors=state.monitors.filter(x=>x.id!==m.id);Object.values(state.months).forEach(x=>delete x[m.id]);currentView='general';saveState()}}}
function renderGeneral(){const scores=state.monitors.map(m=>score(m.id));const count=scores.length||1;const avg=scores.reduce((a,s)=>a+s.points,0)/count;const payroll=scores.reduce((a,s)=>a+s.payment,0);const missed=scores.reduce((a,s)=>a+s.missed,0);const bands=[0,80,100,120].map(b=>scores.filter(s=>s.band===b).length);const deg=bands.map(x=>x/count*360);const d1=deg[0],d2=d1+deg[1],d3=d2+deg[2];const sector=RULES.map((r,i)=>{const gs=scores.map(s=>s.goals[i]);return{...r,avgAtt:gs.reduce((a,g)=>a+g.attainment,0)/count,maxed:gs.filter(g=>g.attainment===1.2).length}});el('mainContent').innerHTML=`${reportHeader('Relatório geral do setor — dados anonimizados')}<section class="page-head"><div><div class="eyebrow">VISÃO DO SETOR • ${monthLabel(state.activeMonth).toUpperCase()}</div><h1>Performance dos monitores</h1><p><span class="anonymous-note">Relatório sem identificação nominal</span></p></div><div class="actions no-print"><button class="btn dark" id="printGeneralBtn">Exportar PDF geral</button></div></section><div class="kpi-grid"><div class="kpi yellow"><small>Média do setor</small><strong>${fmt(avg,1)} pts</strong><span>de 120 pontos possíveis</span></div><div class="kpi green"><small>Remuneração total</small><strong>${money(payroll)}</strong><span>${state.monitors.length} monitores avaliados</span></div><div class="kpi red"><small>Valor não conquistado</small><strong>${money(missed)}</strong><span>comparado ao potencial máximo</span></div><div class="kpi"><small>Na faixa máxima</small><strong>${bands[3]}</strong><span>${fmt(bands[3]/count*100,0)}% do setor</span></div></div><div class="grid-2"><section class="panel"><div class="panel-head"><h2>Distribuição das faixas</h2><span class="panel-sub">sem nomes</span></div><div class="donut-wrap"><div class="donut" style="background:conic-gradient(var(--red) 0 ${d1}deg,#f59e0b ${d1}deg ${d2}deg,var(--yellow) ${d2}deg ${d3}deg,var(--green) ${d3}deg 360deg)"></div><div class="legend">${[['#c73535','0%',bands[0]],['#f59e0b','80%',bands[1]],['#f4c400','100%',bands[2]],['#16834a','120%',bands[3]]].map(x=>`<div class="legend-row"><span class="dot" style="background:${x[0]}"></span><strong>${x[1]}</strong><span>${x[2]} monitor(es)</span></div>`).join('')}</div></div></section><section class="panel"><div class="panel-head"><h2>Atingimento por indicador</h2><span class="panel-sub">média do setor</span></div><div class="sector-metrics">${sector.map(s=>`<div class="sector-row"><header><span>${shortName(s.name)}</span><strong>${pct(s.avgAtt)}</strong></header><div class="chart-track" style="margin-top:8px"><div class="chart-fill ${s.avgAtt>=1.2?'green':''}" style="width:${Math.min(100,s.avgAtt/1.2*100)}%"></div></div><small>${s.maxed} de ${state.monitors.length} na faixa máxima</small></div>`).join('')}</div></section></div><div class="analysis-box"><h3>Leitura executiva do setor</h3><p>${generalAnalysis(scores,sector,payroll,missed)}</p></div>`;el('printGeneralBtn').onclick=()=>window.print()}
function generalAnalysis(scores,sector,payroll,missed){if(!scores.length)return 'Cadastre os monitores e informe os resultados do mês para gerar a análise.';const critical=[...sector].sort((a,b)=>a.avgAtt-b.avgAtt)[0];const max=scores.filter(s=>s.band===120).length;return `O setor possui ${scores.length} monitor(es), com ${max} na faixa máxima. A remuneração calculada é ${money(payroll)} e o valor não conquistado em relação ao máximo é ${money(missed)}. O indicador que mais exige atenção é “${critical.name}”, com atingimento médio de ${pct(critical.avgAtt)}.`}

el('monthInput').onchange=e=>{state.activeMonth=e.target.value;saveState()};
el('addMonitorBtn').onclick=()=>{el('monitorName').value='';el('monitorDialog').showModal()};
el('monitorForm').onsubmit=e=>{if(e.submitter?.value==='cancel')return;const name=el('monitorName').value.trim();if(!name){e.preventDefault();return}let id=name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');if(state.monitors.some(m=>m.id===id))id+=`-${Date.now().toString().slice(-4)}`;state.monitors.push({id,name});currentView=id;saveState();toast('Monitor adicionado')};
el('exportJsonBtn').onclick=()=>{const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`backup-metas-monitores-${state.activeMonth}.json`;a.click();URL.revokeObjectURL(a.href);toast('Backup JSON exportado')};
el('importJsonInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const imported=JSON.parse(await file.text());if(!imported.monitors||!imported.months)throw new Error();if(confirm('Importar este backup substituirá os dados atuais. Continuar?')){state=imported;currentView='general';saveState();toast('Backup restaurado')}}catch{alert('Arquivo JSON inválido ou incompatível.')}e.target.value=''};
render();

function registerWebMcp(){const context=document.modelContext;if(!context?.registerTool)return;const register=tool=>Promise.resolve(context.registerTool(tool)).catch(()=>{});register({name:'read_sector_summary',title:'Consultar resumo do setor',description:'Retorna o resumo anonimizado da competência atual, sem nomes dos monitores.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(){const scores=state.monitors.map(m=>score(m.id));return{competencia:state.activeMonth,quantidadeMonitores:scores.length,pontuacaoMedia:scores.length?scores.reduce((a,s)=>a+s.points,0)/scores.length:0,remuneracaoTotal:scores.reduce((a,s)=>a+s.payment,0),valorNaoConquistado:scores.reduce((a,s)=>a+s.missed,0)}}});register({name:'set_monitor_month_results',title:'Lançar resultados mensais',description:'Atualiza os cinco resultados de um monitor cadastrado na competência informada.',inputSchema:{type:'object',properties:{monitorId:{type:'string'},competencia:{type:'string',pattern:'^\\d{4}-\\d{2}$'},rnc:{type:'number',minimum:0},dss:{type:'number',minimum:0},speed:{type:'number',minimum:0},disciplinary:{type:'number',minimum:0,maximum:1},critical:{type:'number',minimum:0}},required:['monitorId','competencia','rnc','dss','speed','disciplinary','critical'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!state.monitors.some(m=>m.id===input.monitorId))throw new Error('Monitor não encontrado');state.activeMonth=input.competencia;state.months[input.competencia]??={};state.months[input.competencia][input.monitorId]={rnc:input.rnc,dss:input.dss,speed:input.speed,disciplinary:input.disciplinary,critical:input.critical};saveState();return{monitorId:input.monitorId,competencia:input.competencia,...score(input.monitorId)}}})}
registerWebMcp();
